### ISSUE TITLE
testing depends on PLONE_FIXTURE which does not even provide content types in Plone5

### ISSUE THREAD

**Issue by do3cc** [collective/bobtemplates.plone#1]
otoh this might be a bug in plone.app.testing...

**Comment by pbauer** [comment]
Since the eggs created with bobtemplates.plone should also work in Plone 4 without plone.app.contenttypes you'd have to to the test-setup with types yourself with plone.app.contenttypes.testing.PLONE_APP_CONTENTTYPES_FIXTURE.

**Comment by do3cc** [comment]
It makes very much sense to have this there at least as a comment

**Comment by pbauer** [comment]
fixed. When choosing a version of Plone 5 the tests now use PLONE_APP_CONTENTTYPES_FIXTURE
